export interface TenantProfile {
  name: string;
  subdomain: string;
  plan: string;
  initialBranches: number;
  maxBranches: number;
  profile: 'giant' | 'growth' | 'churn' | 'b2c' | 'stable' | 'premium' | 'family' | 'youth' | 'kids' | 'formal';
  activeSinceMonth: number; // 0 = from the start, 3 = starts month 4, etc.
  churnMonth?: number; // month when subscription goes past_due/canceled
  upgradePlan?: { month: number; newPlan: string; newBranches: number };
  dailySalesRange: [number, number]; // [min, max] sales per day per branch
  onlinePercentage: number; // 0-100, what % of sales come from mobile/online
  returnRate: number; // 0-1, probability of return per sale
  layawayRate: number; // 0-1, probability of layaway per day
  creditRate: number; // 0-1, probability of credit sale
  expenseFrequency: number; // avg expenses per day per branch
  transferFrequency: number; // avg transfers per week
  auditFrequency: number; // audits per month
  supportTicketRate: number; // tickets per month
  loyaltyActive: boolean;
  razonSocial: string;
  rfc: string;
  regimenFiscal: string;
  codigoPostalFiscal: string;
}

export const TENANT_PROFILES: TenantProfile[] = [
  {
    name: 'Calzados 3 Hermanos',
    subdomain: '3hermanos',
    plan: 'enterprise',
    initialBranches: 10,
    maxBranches: 10,
    profile: 'giant',
    activeSinceMonth: 0,
    dailySalesRange: [15, 45],
    onlinePercentage: 15,
    returnRate: 0.08,
    layawayRate: 0.12,
    creditRate: 0.05,
    expenseFrequency: 3,
    transferFrequency: 5,
    auditFrequency: 2,
    supportTicketRate: 3,
    loyaltyActive: true,
    razonSocial: 'Calzados 3 Hermanos SA de CV',
    rfc: 'C3H190523AB1',
    regimenFiscal: '601',
    codigoPostalFiscal: '72000',
  },
  {
    name: 'Zapaterías La Bota',
    subdomain: 'labota',
    plan: 'free',
    initialBranches: 1,
    maxBranches: 3,
    profile: 'growth',
    activeSinceMonth: 0,
    upgradePlan: { month: 3, newPlan: 'pro', newBranches: 3 },
    dailySalesRange: [5, 18],
    onlinePercentage: 20,
    returnRate: 0.05,
    layawayRate: 0.08,
    creditRate: 0.02,
    expenseFrequency: 1,
    transferFrequency: 2,
    auditFrequency: 1,
    supportTicketRate: 2,
    loyaltyActive: false,
    razonSocial: 'Zapaterías La Bota SC',
    rfc: 'ZLB200115CD3',
    regimenFiscal: '612',
    codigoPostalFiscal: '44100',
  },
  {
    name: 'Shoe Palace MX',
    subdomain: 'shoepalace',
    plan: 'starter',
    initialBranches: 2,
    maxBranches: 2,
    profile: 'churn',
    activeSinceMonth: 0,
    churnMonth: 2,
    dailySalesRange: [8, 22],
    onlinePercentage: 10,
    returnRate: 0.10,
    layawayRate: 0.04,
    creditRate: 0.01,
    expenseFrequency: 2,
    transferFrequency: 1,
    auditFrequency: 0,
    supportTicketRate: 8,
    loyaltyActive: false,
    razonSocial: 'Shoe Palace México SA de CV',
    rfc: 'SPM180812EF5',
    regimenFiscal: '601',
    codigoPostalFiscal: '64000',
  },
  {
    name: 'PisaFirme Online',
    subdomain: 'pisafirme',
    plan: 'pro',
    initialBranches: 1,
    maxBranches: 1,
    profile: 'b2c',
    activeSinceMonth: 0,
    dailySalesRange: [3, 10],
    onlinePercentage: 80,
    returnRate: 0.12,
    layawayRate: 0.15,
    creditRate: 0.00,
    expenseFrequency: 1,
    transferFrequency: 0,
    auditFrequency: 1,
    supportTicketRate: 1,
    loyaltyActive: true,
    razonSocial: 'PisaFirme Comercio Digital SA de CV',
    rfc: 'PCD210301GH7',
    regimenFiscal: '601',
    codigoPostalFiscal: '06000',
  },
  {
    name: 'El Paso del Norte',
    subdomain: 'elpaso',
    plan: 'basico',
    initialBranches: 3,
    maxBranches: 3,
    profile: 'stable',
    activeSinceMonth: 0,
    dailySalesRange: [8, 20],
    onlinePercentage: 5,
    returnRate: 0.04,
    layawayRate: 0.10,
    creditRate: 0.06,
    expenseFrequency: 2,
    transferFrequency: 2,
    auditFrequency: 1,
    supportTicketRate: 1,
    loyaltyActive: false,
    razonSocial: 'Calzado El Paso del Norte SC de RL',
    rfc: 'CPN170610IJ9',
    regimenFiscal: '612',
    codigoPostalFiscal: '37000',
  },
  {
    name: 'Flexi Outlet Puebla',
    subdomain: 'flexioutlet',
    plan: 'pro',
    initialBranches: 2,
    maxBranches: 2,
    profile: 'premium',
    activeSinceMonth: 0,
    dailySalesRange: [12, 30],
    onlinePercentage: 25,
    returnRate: 0.03,
    layawayRate: 0.06,
    creditRate: 0.04,
    expenseFrequency: 2,
    transferFrequency: 3,
    auditFrequency: 2,
    supportTicketRate: 1,
    loyaltyActive: true,
    razonSocial: 'Distribuidora Flexi Outlet Puebla SA de CV',
    rfc: 'DFO190214KL2',
    regimenFiscal: '601',
    codigoPostalFiscal: '72000',
  },
  {
    name: 'Zapatería Don Julio',
    subdomain: 'donjulio',
    plan: 'free',
    initialBranches: 1,
    maxBranches: 1,
    profile: 'family',
    activeSinceMonth: 1,
    dailySalesRange: [3, 10],
    onlinePercentage: 0,
    returnRate: 0.02,
    layawayRate: 0.20,
    creditRate: 0.10,
    expenseFrequency: 1,
    transferFrequency: 0,
    auditFrequency: 0,
    supportTicketRate: 0.5,
    loyaltyActive: false,
    razonSocial: 'Julio Mendoza Pérez',
    rfc: 'MEPJ750812MN4',
    regimenFiscal: '612',
    codigoPostalFiscal: '90000',
  },
  {
    name: 'Urban Kicks MX',
    subdomain: 'urbankicks',
    plan: 'pro',
    initialBranches: 4,
    maxBranches: 4,
    profile: 'youth',
    activeSinceMonth: 0,
    dailySalesRange: [10, 28],
    onlinePercentage: 40,
    returnRate: 0.06,
    layawayRate: 0.05,
    creditRate: 0.01,
    expenseFrequency: 2,
    transferFrequency: 4,
    auditFrequency: 1,
    supportTicketRate: 2,
    loyaltyActive: true,
    razonSocial: 'Urban Kicks México SA de CV',
    rfc: 'UKM200601OP6',
    regimenFiscal: '601',
    codigoPostalFiscal: '14000',
  },
  {
    name: 'Mundo Infantil',
    subdomain: 'mundoinfantil',
    plan: 'basico',
    initialBranches: 2,
    maxBranches: 2,
    profile: 'kids',
    activeSinceMonth: 0,
    dailySalesRange: [6, 16],
    onlinePercentage: 30,
    returnRate: 0.07,
    layawayRate: 0.14,
    creditRate: 0.03,
    expenseFrequency: 1,
    transferFrequency: 1,
    auditFrequency: 1,
    supportTicketRate: 1,
    loyaltyActive: true,
    razonSocial: 'Mundo Infantil Calzado SA de CV',
    rfc: 'MIC210815QR8',
    regimenFiscal: '601',
    codigoPostalFiscal: '76000',
  },
  {
    name: 'Eleganza Zapatos',
    subdomain: 'eleganza',
    plan: 'starter',
    initialBranches: 1,
    maxBranches: 1,
    profile: 'formal',
    activeSinceMonth: 2,
    dailySalesRange: [2, 8],
    onlinePercentage: 15,
    returnRate: 0.03,
    layawayRate: 0.18,
    creditRate: 0.08,
    expenseFrequency: 1,
    transferFrequency: 0,
    auditFrequency: 1,
    supportTicketRate: 0.5,
    loyaltyActive: false,
    razonSocial: 'Eleganza Calzado Fino SC',
    rfc: 'ECF220301ST0',
    regimenFiscal: '612',
    codigoPostalFiscal: '97000',
  },
];
